# Generated by Django 4.2.3 on 2023-07-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email_subject', models.CharField(max_length=500)),
                ('descsription', models.TextField()),
            ],
        ),
    ]
